{% set name = "simple_slurm" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c439e5c756ca9e5f600c4f54cdbf31d44c91330db60b1854a0f244acc6f2d300

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - simple_slurm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amq92/simple_slurm
  summary: A simple Python wrapper for Slurm with flexibility in mind.
  license: AGPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - amq92
