{% set name = "simple_slurm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffc2d36f9e91791788c98e873a68072c7d0c8d727744fcbb8ff09dd2dbf3d9df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - simple_slurm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amq92/simple_slurm
  summary: A simple Python wrapper for Slurm with flexibility in mind.
  license: AGPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - amq92
